import {
	DOMParser,
	type Document,
	type Element,
	type Node,
	XMLSerializer,
} from '@xmldom/xmldom';

export interface PdfaIdentification {
	part: 1 | 2 | 3 | 4;
	conformance: 'A' | 'B' | 'U' | 'E';
}

export interface DublinCoreMetadata {
	title?: string;
	creator?: string[];
	description?: string;
	subject?: string[];
}

export class XmpDocument {
	private doc: Document;

	private static readonly NS_X = 'adobe:ns:meta/';
	private static readonly NS_RDF =
		'http://www.w3.org/1999/02/22-rdf-syntax-ns#';
	private static readonly NS_DC = 'http://purl.org/dc/elements/1.1/';

	private constructor(doc: Document) {
		this.doc = doc;
	}

	/**
	 * Parses a raw XMP XML string or creates a blank minimal XMP packet.
	 */
	static parse(xmlString?: string): XmpDocument {
		if (!xmlString || xmlString.trim() === '') {
			xmlString = XmpDocument.createEmpty();
		}

		const doc = new DOMParser().parseFromString(xmlString, 'text/xml');

		return new XmpDocument(doc);
	}

	private static createEmpty(): string {
		const bom = '\uFEFF';
		return `<?xpacket begin="${bom}" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/">
	<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
		<rdf:Description rdf:about="" />
	</rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>`;
	}

	setPdfaConformance(pdfa: PdfaIdentification): void {
		// TODO!
	}

	setDublinCore(dc: DublinCoreMetadata): void {
		const desc = this.getOrCreateDocumentDescriptionNode();

		const formatElem = this.doc.createElementNS(
			'http://purl.org/dc/elements/1.1/',
			'dc:format',
		);

		formatElem.appendChild(this.doc.createTextNode('application/pdf'));

		desc.appendChild(this.doc.createTextNode('\n\t\t\t'));
		desc.appendChild(formatElem);
		desc.appendChild(this.doc.createTextNode('\n\t\t'));

	}

	injectRawDescription(xmlSnippet: string): void {
		if (!xmlSnippet || xmlSnippet.trim() === '') {
			return;
		}

		// Wrap the snippet in a temporary root to ensure valid XML even if
		// the user passed multiple sibling <rdf:Description> elements.
		const wrappedXml = `<fragment xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">${xmlSnippet}</fragment>`;

		const snippetDoc = new DOMParser().parseFromString(wrappedXml, 'text/xml');
		const root = snippetDoc.documentElement;

		if (!root) {
			throw new Error('Failed to parse XML snippet: documentElement is null.');
		}

		// Check for XML parsing error nodes generated by DOMParser
		const parserError = root.getElementsByTagName('parsererror');
		if (parserError.length > 0) {
			throw new Error(
				`Invalid XML snippet: ${parserError.item(0)?.textContent ?? 'Parse error'}`,
			);
		}

		const rdfNode = this.getOrCreateRdfNode();

		// Iterate over all child nodes (elements, comments) inside the fragment
		const childNodes = Array.from(root.childNodes);
		for (const child of childNodes) {
			// Only import Element nodes (nodeType 1) and Comment nodes (nodeType 8)
			if (child.nodeType === 1 || child.nodeType === 8) {
				const importedNode = this.doc.importNode(child, true);
				rdfNode.appendChild(importedNode);
			}
		}
	}

	serialize(): string {
		return new XMLSerializer().serializeToString(this.doc);
	}

	private getOrCreateRdfNode(): Element {
		const rdfNodes = this.doc.getElementsByTagNameNS(XmpDocument.NS_RDF, 'RDF');
		if (rdfNodes.length > 0) {
			return rdfNodes.item(0)!;
		}

		// Fallback: Try tag name lookup in case namespaces weren't bound strictly
		const fallbackRdf = this.doc.getElementsByTagName('rdf:RDF');
		if (fallbackRdf.length > 0) {
			return fallbackRdf.item(0)!;
		}

		// If missing, locate or create <x:xmpmeta>
		const xmpMetaNode = this.getOrCreateXmpMetaNode();

		// Create and attach <rdf:RDF>
		const newRdf = this.doc.createElementNS(XmpDocument.NS_RDF, 'rdf:RDF');
		xmpMetaNode.appendChild(newRdf);

		return newRdf;
	}

	private getOrCreateXmpMetaNode(): Element {
		const metaNodes = this.doc.getElementsByTagNameNS(
			XmpDocument.NS_X,
			'xmpmeta',
		);
		if (metaNodes.length > 0) {
			return metaNodes.item(0)!;
		}

		const fallbackMeta = this.doc.getElementsByTagName('x:xmpmeta');
		if (fallbackMeta.length > 0) {
			return fallbackMeta.item(0)!;
		}

		// Create root <x:xmpmeta> element
		const newMeta = this.doc.createElementNS(XmpDocument.NS_X, 'x:xmpmeta');
		this.doc.appendChild(newMeta);

		return newMeta;
	}

	public getOrCreateDocumentDescriptionNode(): Element {
		const rdfNode = this.getOrCreateRdfNode();
		const descriptions = rdfNode.getElementsByTagNameNS(
			XmpDocument.NS_RDF,
			'Description',
		);

		// Look for an <rdf:Description> without an explicit subject or with
		// rdf:about="".
		for (let i = 0; i < descriptions.length; i++) {
			const desc = descriptions.item(i);
			if (
				desc &&
				(!desc.hasAttribute('rdf:about') ||
					desc.getAttribute('rdf:about') === '')
			) {
				return desc;
			}
		}

		// Create a new <rdf:Description rdf:about="">
		const newDesc = this.doc.createElementNS(
			XmpDocument.NS_RDF,
			'rdf:Description',
		);
		newDesc.setAttributeNS(XmpDocument.NS_RDF, 'rdf:about', '');
		rdfNode.appendChild(newDesc);

		return newDesc;
	}
}
