name: CI - Push Test Suite

on:
  push:
    branches:
      - '**'

concurrency:
  group: ci-quick-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test on ${{ matrix.os }} with Node.js ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [24]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6


      - name: List Linux Fonts
        if: matrix.os == 'ubuntu-latest'
        run: ls -R /usr/share/fonts

      - name: List macOS Fonts
        if: matrix.os == 'macos-latest'
        run: ls -R /System/Library/Fonts

      - name: List MS-DOS Fonts
        shell: cmd # We need the crap shell!
        if: matrix.os == 'windows-latest'
        run: dir /s C:\Windows\Fonts

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up pnpm
        uses: pnpm/action-setup@v5
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Build
        run: pnpm run build

      - name: Run tests
        run: pnpm run test
