name: Release

permissions:
  contents: write
  pull-requests: write
  id-token: write

on:
  push:
    branches:
      - main

  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Setup Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Set up pnpm
        uses: pnpm/action-setup@v5
        with:
          version: 10

      - name: Install Dependencies
        run: pnpm install

      - name: Show changeset status
        run: npx changeset status

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run release
        env:
          HUSKY: 0
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
